# Setup
language: pt_BR
lang: pt_BR
locale: "pt-BR"
title: Nova Igreja de Cascavel
tagline: "Meditações semanais"
description: 'Meditações semanais utilizadas nos grupos de amigos da Nova Igreja de Cascavel.'
url: https://tetri.github.io/NIBMeditacoes/
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Tetri Mesquita
  url: https://tetri.dev
  email: contato@tetri.dev

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 0.0.1
google_analytics_id: #UA-XXXX-Y